### ISSUE TITLE
Add basic 'style.css'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/earthquake-finder#110]
We will add a primitive `style.css` which will define the following:

``` css
.ajax_loader {
  background: url('../img/loading.gif') no-repeat center center transparent;
  background-size:90px 90px;
  width:100%; height:100%;
}
```
